### PR TITLE
Daily log mvp

### LINKED ISSUE #27: Daily Log page- CRUD functionality, styling, history of past logs
**Required features:**

- CRUD functionality- JavaScript + local storage/IndexDB
- Styling and CSS
- Prompts + History of logs + sorted by date (can use last week’s lab as inspiration)
- Follow Figma design

### PR DESCRIPTION
**Pull request by mho04**
## Pull request summary:
Adding calendar feature causing most of the javascript and css code needing to change
-now needs: to make the logs save to local storage

## Type of change (bug, feature, design, logistics, etc):
Fixed individual buggyness of saving new entries vs editing existing ones

Changes design of webpage,
New Features:
- functional calendar 
- entry logs linked to their corresponding day

## How has this been tested (if applicable):
Tested
Calendar's
- prev and next buttons work and go to their corresponding month
- the dates are aligned with the real life calendar days
- days that are being click has a selected appearance
- days that have entry logs have an indicator via background of their day darkening

Calendar had two dropdowns, one for the month and one for the year to quickly change month & year but I didn't implement code that automatically updated their location when screen was resized causing it to block some things on the screen so for now I just took it out

Entry logs's
- each day has its own log
- the date of the day selected (on the log) tested to change when selection changes: on my device for some reason the selected date one displayed was a month ahead and one day behind so there's code to specifically counteract that. Unsure if it will be the same for other people
- can be saved even if only one box has words in it
- button to delete individually works
- button to be deleted all at once works

Made sure the sizing of every element remained flex to adjust to the size of the screen so in theory should work on mobile.

## Checklist:
- [ X] I have performed a self-review of my own code
- [ X] I have tested that my changes work (locally and via unit testing)
- [ ] I have assigned atleast 2 reviewers to look at and review my code quality
- [ X] Documentation has been updated
- [ ] Code follows style guidelines

### CODE REVIEW

**Review by ronadarabi — APPROVED** [review]
I looked up the remaining Codacy error and it can be ignored according to the internet.

**Review by NathanTzChung — COMMENTED** [review]
CSS
- Looks good, though I think the right side of the form section gets covered as the webpage gets smaller.

JS
- Looks good as well (in regards to the code itself). However, I don't actually see the JS working on the page. I am unable to see the dates populated for the calendar and the left/right arrows to change months doesn't work. One of the comments inside the JS page says that the JS works though the CSS is buggy (but that might be for a different functionality than the ones mentioned above)

**Review by NathanTzChung — APPROVED** [review]
CSS
- Looks good, though I think the right side of the form section gets covered as the webpage gets smaller.

JS
- Looks good as well (in regards to the code itself). However, I don't actually see the JS working on the page. I am unable to see the dates populated for the calendar and the left/right arrows to change months doesn't work. One of the comments inside the JS page says that the JS works though the CSS is buggy (but that might be for a different functionality than the ones mentioned above)

**Review by yashilvora19 — APPROVED** [review]
Work needs to be done on styling to make sure page works on tablet, mobile and desktop. Overall look is nice, great work with CRUD functionality. Testing will be important for this page in the next sprint!

**Pull request merged**
