### PR TITLE
Homepage projects crud

### LINKED ISSUE #76: HOMEPAGE- CRUD for Projects
Integrating CRUD functionality for the projects section of the homepage. This includes:

- Starting with no projects
- Using the + button to add projects
- Implementing delete functionality in the dustbin button
- Making sure that the data is kept in localStorage
- UI for adding and editing projects is improved

Once this is complete, delete all code for the projects page

### PR DESCRIPTION
**Pull request by yashilvora19**
## Pull request summary:
- LocalStorage functionality added
- CSS for styling the form
- Adding and deleting functionality added
- Deleting is a little bit buggy- it only works after I refresh the page once
- Redundant projects page files deleted
- Code cleaned up

## Type of change (bug, feature, design, logistics, etc):
Feature

## How has this been tested (if applicable):
Tested locally- Junit tests will be done in other issues

## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have tested that my changes work (locally and via unit testing)
- [x] I have assigned atleast 2 reviewers to look at and review my code quality
- [x] Documentation has been updated
- [x] Code follows style guidelines

### CODE REVIEW

**Review by ronadarabi — APPROVED** [review]
This is awesome I'm really happy with it!!!

**Review by caz002 — APPROVED** [review]
Nice job, the homepage and editing form look good! I think it was good idea to make the projects one color to make coding the CRUD simpler. I like the shadows that were added, they make the items pop more. The task animation is showing up a little buggy for me, but that may just be my computer.

**Review by NathanTzChung — APPROVED** [review]
I think the CRUD portion is great! As for styling, there is some issue with the Journal icon on the projects (like it's oversized, at least on my end?), and the project cards are inconsistent (depending on length of text). I think functionality is good to go though! The styling can be worried about if we have time later on as there are more important things I think.

**Comment by yashilvora19** [comment]
> I think the CRUD portion is great! As for styling, there is some issue with the Journal icon on the projects (like it's oversized, at least on my end?), and the project cards are inconsistent (depending on length of text). I think functionality is good to go though! The styling can be worried about if we have time later on as there are more important things I think.

The Journal icon is just 1 line, we can change it to whatever size we want. As for the length of the project cards, I noticed that too, but you are right- we can focus on that if we have time to do so!

**Pull request merged**
