### PR TITLE
Daily Log CSS 

### LINKED ISSUE #36: DAILY LOG: Background color and responsiveness
## Description
Change the Daily Log background to a single color and improve the responsiveness of the different views.

## Acceptance Criteria
- The Daily Log background is a single, unified color.
- The layout adjusts seamlessly to different screen sizes.
- Ensure all elements are responsive and maintain usability across devices.

### PR DESCRIPTION
**Pull request by ronadarabi**
## Pull request summary:
Implemented the navigation bar from the homepage, changed the background to be one color

## Type of change (bug, feature, design, logistics, etc):
Design 

## How has this been tested (if applicable):
Tested locally

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have tested that my changes work (locally and via unit testing)
- [x] I have assigned atleast 2 reviewers to look at and review my code quality
- [x] Documentation has been updated
- [x] Code follows style guidelines

### CODE REVIEW

**Review by mho04 — APPROVED** [review]
Everything I saw looked good and was working.

**Comment by yashilvora19** [comment]
Bypassed static checks because they were just detecting comments

**Review by yashilvora19 — APPROVED** [review]
ADR is well written- concise and clear!
Styling of the page is great, its responsive and works well.

Great work with the homepage daily streak bit as well

**Comment by yashilvora19** [comment]
I also tested out localStorage and the checkboxes functionality and it works pretty well

**Pull request merged**
